application: gae-django-project-template
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /_ah/(mapreduce|queue|warmup).*
  script: project.wsgi.application
  login: admin

- url: /.*
  script: project.wsgi.application